# Generated by Django 3.0.8 on 2020-08-08 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuários',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('user', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliações',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default='Não deixou comentários sobre o estabelecimento.', max_length=300)),
                ('grade', models.IntegerField()),
                ('empresa', models.ManyToManyField(blank=True, related_name='empresa', to='registros.Empresas')),
                ('user', models.ManyToManyField(blank=True, related_name='usuário', to='registros.Usuários')),
            ],
        ),
    ]
