# Generated by Django 3.0.8 on 2020-08-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliações',
            name='avaliador',
            field=models.ManyToManyField(blank=True, related_name='avaliador', to='registros.Usuários'),
        ),
    ]
