# Generated by Django 3.0.8 on 2020-08-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_remove_avaliações_avaliador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresas',
            name='name',
            field=models.CharField(max_length=101),
        ),
    ]
