# Generated by Django 3.0.8 on 2020-08-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_auto_20200809_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='latitude',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='longitude',
            field=models.FloatField(default='0.00'),
        ),
        migrations.AlterField(
            model_name='avaliações',
            name='empresa',
            field=models.ManyToManyField(blank=True, related_name='empresas', to='registros.Empresas'),
        ),
    ]
