# Generated by Django 3.0.8 on 2020-08-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_auto_20200809_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliações',
            name='empresa_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avaliações',
            name='empresaname',
            field=models.CharField(default='Sem nome', max_length=64),
        ),
        migrations.AddField(
            model_name='avaliações',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='avaliações',
            name='username',
            field=models.CharField(default='Sem nome', max_length=64),
        ),
    ]
